[package]
name = "baggo"
version = "0.1.1"
edition = "2024"

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28.3", features = ["extension-module", "abi3-py311"] }
wgpu = "29"
winit = "0.30"
bytemuck = { version = "1", features = ["derive"] }
pollster = "0.3"
image = { version = "0.25", default-features = false, features = ["png"] }
