class Map2D:

    @property
    def width(self) -> int: ...

    @property
    def height(self) -> int: ...

    def in_bounds(self, x: int, y: int) -> bool: ...
    def index(self, x: int, y: int) -> int:...
    def point(self, index: int) -> tuple[int, int]: ...