from typing import Callable

class Algorithm2D:

    @property
    def width(self) -> int: ...

    @property
    def height(self) -> int: ...

    def in_bounds(self, x: int, y: int) -> bool: ...
    def index(self, x: int, y: int) -> int:...
    def point(self, index: int) -> tuple[int, int]: ...

def field_of_view(x: int, y: int, radius: int, fov_check: Algorithm2D, opaque_check: Callable[[int, int], bool]) -> list[tuple[int, int]]: ...