name: Code Quality

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:

  lint:
    name: Code Inspections
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Rust
        run: rustup update stable && rustup default stable

      - name: Install UV
        uses: astral-sh/setup-uv@v7
        with:
          python-version: "3.14"
          enable-cache: true

      - name: Setup Project
        run: uv sync

      - name: Cargo Check
        run: cargo check

      - name: Cargo Formatting
        run: cargo fmt --check

      - name: Ruff Check
        run: uv run ruff check baggo

      - name: Ruff Formatting
        run: uv run ruff format --check baggo

      - name: ty
        run: uv run ty check baggo