name: Publish

on:
  # Called from release workflow
  workflow_call:

env:
  PYTHON_VERSION: "3.14"

jobs:
  pypi-publish:
    name: Release
    runs-on: ubuntu-latest
    environment:
      name: pypi
    permissions:
      id-token: write
    steps:
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - uses: actions/download-artifact@v7
        with:
          pattern: wheels-*
          path: wheels
          merge-multiple: true
      - name: Publish to PyPI
        run: uv publish 'wheels-*/*'
